@startuml
participant Администратор
participant Пользователь
participant Сервис
participant Сообщение
activate Сервис
activate Пользователь
Пользователь -> Администратор: запрос на регистрацию
activate Администратор
Администратор -> Пользователь: регистрация 
deactivate Администратор
Пользователь -> Сервис: подключение
Пользователь -> Сообщение: Отправка сообщения
activate Сообщение
Сообщение -> Пользователь: получение сообщения
deactivate Сообщение 
Пользователь -> Сообщение: Отправка сообщения
activate Сообщение
Сообщение -> Пользователь: получение сообщения
deactivate Сообщение 
Пользователь -> Сообщение: Отправка сообщения
activate Сообщение
Сообщение -> Пользователь: получение сообщения
deactivate Сообщение 
Пользователь -> Сервис: отключение
deactivate Пользователь
Пользователь -> Сервис: подключение
Пользователь -> Сообщение: Отправка сообщения
activate Сообщение
Сообщение -> Пользователь: получение сообщения
deactivate Сообщение 
Пользователь -> Сообщение: Отправка сообщения
activate Сообщение
Сообщение -> Пользователь: получение сообщения
deactivate Сообщение
activate  Пользователь
Пользователь -> Администратор: запрос на аннуляцию
activate Администратор
Администратор -> Пользователь: аннуляция
deactivate Администратор
deactivate Пользователь
deactivate Сервис
@enduml

@startuml

node Пользователь
node Администратор
database Сервис
database Сообщение 
Пользователь .. Администратор: запрос на регистрацию/аннуляцию
Администратор - Пользователь: регистрация/аннулция
Пользователь - Сервис: подключение
Пользователь .. Сервис: отключение
Пользователь - Сообщение: отправка
Пользователь .. Сообщение: получение

@enduml
